# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5de2ceab429a9b5c7721dc1b47ee1ed140b3025214823465d7e6af69122d49748dedc62dbbd9aea8a1c770b4b978eb09e87e744b0a13b224d2e5b4581ac6ed19

test:
  secret_key_base: 6b2500d32753908c3a56c6fed242d53804d9d79ebf0dcc6d2d2aeef915ff07edc2d7ddbefe85b3a22a75a66314cc844162fdba5bd3da0769574e040253ab18a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
