# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c1cebcae217a8ed549433cb2ba7c53ecc14c9510316515ef88e94b0904ca613d45871e2b73fd1b93807c8c7950f2e338c9039844484ce608e00c8c800121c8

test:
  secret_key_base: 279abf5c5d299dce0ae874f7a471901c0152cc20e3b3b4d7944d7f323647f3f26efacb839362f68f9b323eb0c8739891a26a7c9ed4b6e202492543731ecf7ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
